---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: resume-storage-project
  name: resume-storage-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-storage-project
  template:
    metadata:
      labels:
        app: resume-storage-project
        visualize: "true"
    spec:
      containers:
        - name: resume-storage-project
          image: arthurstrokov/resume-storage-project:v0.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: spring.mvc.servlet.path
              value: /resume-storage-project
            - name: SERVER-PORT
              value: "8080"
            - name: EUREKA-DEFAULT-ZONE
              value: "http://192.168.59.106:30001/eureka/"
            - name: EUREKA-INSTANCE-HOSTNAME
              value: resume-storage-project
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: resume-storage-project
  name: resume-storage-project
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/path-rewrite: /
spec:
  selector:
    app: resume-storage-project
  ports:
    - name: resume-storage-project-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
