spring:
  main:
    banner-mode: off
  application:
    name: resume-storage-project
  profiles:
    active: cloud # dev cloud
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      failFast: true
      uri: http://${CONFIG_URL}/ # marathon-lb/marathon-deploy.json
      #      uri: ${CONFIG_URI:http://cloud-configuration-server:8888} # for docker-compose using
      #      uri: http://host.docker.internal:8888/ # or ip inside docker container or localhost for docker container local using
      #      uri: http://localhost:8888/
      retry:
        max-attempts: 6
server:
  port: 8080
---
eureka:
  instance:
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVICE_URI}/eureka
#      defaultZone: ${EUREKA_SERVICE_URI:http://localhost:8761/eureka}
---
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "*" ]
      base-path: "/"
      path-mapping:
        prometheus: metrics
#        enable:
#          http_server_requests: true
