spring:
  main:
    banner-mode: off
  application:
    name: resume-storage-project
  profiles:
    active: cloud
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-configuration-server
      enabled: true
      failFast: true
      retry:
        max-attempts: 6
---
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA-DEFAULT-ZONE:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
    hostname: ${EUREKA-INSTANCE-HOSTNAME:localhost}
---
server:
  port: ${SERVER-PORT:8080}
